
- name: Create data directory for mongodb_config_server configuration
  file:
    path: "{{ mongodb_datadir_prefix }}/configdb"
    state: directory
    owner: "{{ mongodb_system_user_name }}"
    group: "{{ mongodb_system_group_name }}"
  tags: os-mongodb-configdb-create-dir

- name: Templatize /etc/hosts
  template:
    src: mongodb_hosts.j2
    dest: /etc/hosts
    mode: 0644
  register: os_mongodb_config_hosts

- name: Templatize /etc/default/mongod
  template:
    src: mongodb_default.j2
    dest: /etc/default/mongod
    mode: 0644
  register: os_mongodb_config_server_defaults

- name: Templatize upstart job /etc/init/mongod.conf
  template:
    src: mongodb_config_server_upstart.j2
    dest: /etc/init/mongod.conf
    mode: 0655
  register: os_mongodb_config_server_upstart

- name: Fix systemd conf file for mongod
  copy:
    src: systemd_mongod.conf
    dest: /lib/systemd/system/mongod.service
    mode: 0644
  notify:
    - reload systemd
    - restart mongod
  when: ansible_distribution_version == "16.04"

- name: Create the mongo configuration server file
  template:
    src: mongodb_config_server.conf.j2
    dest: /etc/mongod.conf
  register: mongodb_config_server_conf

- name: Copy the keyfile for authentication
  copy:
    src: mongodb_config_server_secret
    dest: "{{ mongodb_datadir_prefix }}/secret"
    owner: "{{ mongodb_system_user_name }}"
    group: "{{ mongodb_system_group_name }}"
    mode: 0400

- name: Restart MongoDB services on file changes
  command: /usr/sbin/service mongod restart
  when: (
    os_mongodb_config_server_defaults.changed
    or os_mongodb_config_server_upstart.changed
    or mongodb_config_server_conf.changed )

- name: Execute handlers
  meta: flush_handlers

- name: auto-start mongod
  service:
    name: mongod
    enabled: yes
