---

- name: reload mongod
  shell: service mongod reload

- name: restart mongod
  shell: service mongod restart

- name: reload systemd
  shell: systemctl daemon-reload
  when: systemd.stat.exists == true and mongodb_manage_service

- name: restart sysfsutils
  service: name=sysfsutils state=restarted
